### PR TITLE
Allow non-printable characters inside quoted string literals.

### PR DESCRIPTION
**Pull request by ghost**
Fixed issue #192

### CODE REVIEW

**Comment by puzrin** [comment]
NB. Speed decrease is ~10% (25% on edge cases). Looks acceptable.

**Comment by dervus** [comment]
Looks good, but

1. Why "JSON-style" input checking is disabled for single quoted scalars? I thought that according to the spec all quoted scalars should follow this exception.

2. Performance probably could be improved by rewriting this regexp to something similar to JSON char check in the same function: https://github.com/nodeca/js-yaml/blob/73c7421f6ee9567c1397631b295ba31be90a3748/lib/js-yaml/loader.js#L245-L255
It was written this way exactly becasue of performance. Manual codepoint-by-codepoint iteration is faster on small inputs than regexp test.

**Comment by a-rodin** [comment]
Disabling of the JSON-style checking for single quoted scalars is a consequence of the following two statements:
a) 5.7. Note that escape sequences are only interpreted in double-quoted scalars
b) 5.1. To ensure readability, non-printable characters should be escaped on output, even inside such scalars.
If there is an non-printable character inside double-quoted scalar, then after parsing and exporting it should be replaced by escape sequence because of b). But it is impossible because of a). So the only way to resolve this problem is to assume that non-printable characters are allowed only inside double-quoted scalars, but not single-quoted ones.

**Comment by dervus** [comment]
You're mixing two independent areas. 5.1 is dumper's concern. Dumper takes JS object and then decides by itself which scalar style to use. 5.7 is out of place at all. It's about `\` escape sequences, no?

I'm just looking for usage of `nb-json` rule, and see that it's base for both `nb-double-char` and `nb-single-char`. See grammer rules in "7.3.1. Double-Quoted Style" and "7.3.2. Single-Quoted Style".

**Comment by a-rodin** [comment]
OK, I've missed the section 7.3.2, so I'll revert the check for single-quoted scalars back.

**Comment by dervus** [comment]
@puzrin, if you think we don't need to try improve the performance, then It's good for merge now,

**Comment by puzrin** [comment]
I doubt that regexp unroll for this case will be faster - too many conditions. Let's leave it for someone else, who has time for experiments.

**Pull request merged**
