### PR TITLE
don't use block-style-only string literals in flow mode

### PR DESCRIPTION
**Pull request by shaunc**
Here is a fix to https://github.com/nodeca/js-yaml/issues/235. I included a test, but I didn't understand your test numbering system.

### CODE REVIEW

**Comment by shaunc** [comment]
btw ... I tried to install eslint but ... 

$ make lint
Invalid option '--reset' - perhaps you meant '--ext'?
make: *** [lint] Error 1

(I am more familiar with js-hint...)

If you need an explicit version, perhaps better to point the `Makefile` at `node_modules/.bin/eslint` rather than depend on global version?

**Comment by shaunc** [comment]
(slap-on-head -- test numbering system isn't so complex :))

**Comment by dervus** [comment]
Seems good, but could you squish it into single commit?

**Comment by shaunc** [comment]
How's that? I think I got the squash right this time. :)

**Comment by dervus** [comment]
Thanks!

**Pull request merged**
