### PR TITLE
Fix date parsing

### LINKED ISSUE #268: js-yaml timestamp regexp is more liberal than the standard
From http://yaml.org/type/timestamp.html
> Regexp:
> ```
 [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] # (ymd)
|[0-9][0-9][0-9][0-9] # (year)
 -[0-9][0-9]? # (month)
 -[0-9][0-9]? # (day)
 ([Tt]|[ \t]+)[0-9][0-9]? # (hour)
 :[0-9][0-9] # (minute)
 :[0-9][0-9] # (second)
 (\.[0-9]*)? # (fraction)
 (([ \t]*)Z|[-+][0-9][0-9]?(:[0-9][0-9])?)? # (time zone)
```

The first form (ymd) does not allow single digit days or months, but the regex in [`js-yaml/type/timestamp` ](https://github.com/nodeca/js-yaml/blob/5f058c3a78fd1a1bd36fd2cdc2c3a8c45ab53fd1/lib/js-yaml/type/timestamp.js#L5) will allow this.

### PR DESCRIPTION
**Pull request by dplepage**
Fixes #268.

### CODE REVIEW

**Comment by puzrin** [comment]
Did you checked benchmark? I understand problem, but don't like idea to increase number of regex calls.

**Comment by dplepage** [comment]
The benchmark results look pretty similar on my machine, but this is by no means exhaustive. It doesn't look like any of the benchmark samples actually contain timestamps, so this is really only checking the slowdown of `resolveYamlTimestamp`. The differences appear to be within the variance I see from just running the benchmark multiple times.

### Before
```
Sample: document_application2.yaml (360 characters)
 > current x 40,145 ops/sec ±1.55% (81 runs sampled)
Sample: document_huge.yaml (7182063 characters)
 > current x 4.99 ops/sec ±3.08% (15 runs sampled)
Sample: document_nodeca_application.yaml (2055 characters)
 > current x 33,652 ops/sec ±1.11% (89 runs sampled)
Sample: document_nodeca_database.yaml (394 characters)
 > current x 73,385 ops/sec ±1.56% (85 runs sampled)
Sample: document_nodeca_logger.yaml (727 characters)
 > current x 25,125 ops/sec ±1.51% (83 runs sampled)
Sample: scalar_double_quoted_binary_01.yaml (807 characters)
 > current x 129,090 ops/sec ±0.92% (86 runs sampled)
Sample: scalar_double_quoted_binary_02.yaml (12007 characters)
 > current x 8,955 ops/sec ±0.89% (83 runs sampled)
Sample: scalar_double_quoted_escaped_01.yaml (119 characters)
 > current x 522,485 ops/sec ±1.32% (85 runs sampled)
Sample: scalar_double_quoted_escaped_02.yaml (3444 characters)
 > current x 35,455 ops/sec ±1.58% (84 runs sampled)
Sample: scalar_double_quoted_simple_01.yaml (107 characters)
 > current x 774,084 ops/sec ±1.21% (86 runs sampled)
Sample: scalar_double_quoted_simple_02.yaml (3353 characters)
 > current x 40,661 ops/sec ±1.27% (87 runs sampled)
Sample: scalar_double_quoted_simple_multiline.yaml (2707 characters)
 > current x 37,276 ops/sec ±1.09% (85 runs sampled)
```

### After
```
Sample: document_application2.yaml (360 characters)
> current x 41,155 ops/sec ±1.75% (81 runs sampled)
Sample: document_huge.yaml (7182063 characters)
> current x 5.09 ops/sec ±2.67% (15 runs sampled)
Sample: document_nodeca_application.yaml (2055 characters)
> current x 32,444 ops/sec ±0.77% (88 runs sampled)
Sample: document_nodeca_database.yaml (394 characters)
> current x 83,429 ops/sec ±1.52% (84 runs sampled)
Sample: document_nodeca_logger.yaml (727 characters)
> current x 24,824 ops/sec ±0.93% (88 runs sampled)
Sample: scalar_double_quoted_binary_01.yaml (807 characters)
> current x 121,229 ops/sec ±0.75% (86 runs sampled)
Sample: scalar_double_quoted_binary_02.yaml (12007 characters)
> current x 9,258 ops/sec ±0.82% (88 runs sampled)
Sample: scalar_double_quoted_escaped_01.yaml (119 characters)
> current x 560,702 ops/sec ±1.09% (86 runs sampled)
Sample: scalar_double_quoted_escaped_02.yaml (3444 characters)
> current x 25,252 ops/sec ±1.34% (88 runs sampled)
Sample: scalar_double_quoted_simple_01.yaml (107 characters)
> current x 772,908 ops/sec ±0.96% (88 runs sampled)
Sample: scalar_double_quoted_simple_02.yaml (3353 characters)
> current x 40,198 ops/sec ±0.96% (88 runs sampled)
Sample: scalar_double_quoted_simple_multiline.yaml (2707 characters)
> current x 42,134 ops/sec ±0.99% (90 runs sampled)
```

**Comment by puzrin** [comment]
Ок, if benchmarks did not suffered - i see no problems.

/cc @dervus ?

**Comment by dervus** [comment]
LGFM.

**Pull request merged**
