### PR TITLE
Added support for async functions

### PR DESCRIPTION
**Pull request by GeekyDeaks**
Hi,

This is my attempt to provide support for async functions.  I encountered the same problem as #414 and figured I'd take a quick look to see if it was an easy fix.

Unfortunately, it required a change to the eslint config, which I am not entirely happy about.   Maybe it would be better to provide override statements?

### CODE REVIEW

**Comment by GeekyDeaks** [comment]
Yep - failing on older versions!

Ok, I'm going to have a think about how best to fix it, but if you have any suggestions on a suitable approach I am all ears

**Comment by puzrin** [comment]
I don't like idea to move into lang-specific direction in core. IMO it's better to keep such specific thing as "plugin". Implementation allows to extend schemas as you wish.

**Comment by GeekyDeaks** [comment]
I think I understand what you mean.  So we would have something like:

`function: !!js/asyncfunction 'async () => { }'`

Correct?

**Comment by puzrin** [comment]
That's one on possibilities. Or you can reassemble schema, using your own implementation for `!!js/function` instead of built-in one.

**Comment by GeekyDeaks** [comment]
I like the idea of the plugin too, so I'll close this PR and write one.

Would it be of any use for me to create another PR to place the plugin in `/examples` and link it to #414?

**Comment by GeekyDeaks** [comment]
Sorry @puzrin, can I re-open this please?

I'm having trouble `dump()`ing using a plugin.  There seems to be an explicit check in the core code for a function:

https://github.com/nodeca/js-yaml/blob/665aadda42349dcae869f12040d9b10ef18d12da/lib/js-yaml/dumper.js#L671-L672

I'm trying to figure out how to override this in a plugin...

**Comment by GeekyDeaks** [comment]
I forgot to mention - the `dump()` works correctly with the PR, so there is something going on I cannot quite fathom

**Comment by GeekyDeaks** [comment]
Sorry @puzrin - it was a mistake in my plugin.  Apologies for hassling you with this.  I'll close this one now.

**Pull request closed without merging**
