### PR TITLE
Add option to specify max line width.

### PR DESCRIPTION
**Pull request by IvanGoncharov**

### CODE REVIEW

**Comment by puzrin** [comment]
Just one question. Is it really necessary to tune width?

**Comment by IvanGoncharov** [comment]
In my case yes, I do some transformations on handwritten YAML files and compare them afterwards.
I work with API descriptions and it most of the cases they have quite long descriptions inside YAML.
For example:  https://github.com/darklynx/swagger-api-collection/blob/master/api/yaml/instagram.yaml#L18
So my intent is to set this values as `-1`.

I took semantic from here: http://stackoverflow.com/questions/17859864/why-does-psych-yaml-interpreter-add-line-breaks-around-80-characters
So I think it useful not only to me :smile:

**Comment by IvanGoncharov** [comment]
Wow it was super fast :+1:

**Comment by puzrin** [comment]
Ok. If you dig closed tickets, you can see that i postponed this feature until someone say "yes i need it" :)

**Comment by IvanGoncharov** [comment]
I found it: https://github.com/nodeca/js-yaml/pull/215#issuecomment-150834932
@puzrin Can you please make release?
This change is blocking me + it allow me to workaround #222

**Comment by puzrin** [comment]
done

**Comment by IvanGoncharov** [comment]
Thanks a lot

**Pull request merged**
