### PR TITLE
Improve browserify support

### LINKED ISSUE #230: Don't include esprima in the browser bundle
In [function.js](https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/js/function.js) there is a try/catch around a require statement. Browserify will find that require statement and still include esprima in the browser bundle.

Using browserify, you can use the ["browser" field](https://github.com/substack/browserify-handbook#browser-field) like this...
```json
  "browser": {
    "esprima": false
  },
````
...to make `require('esprima')` return an empty object in the browser.

### PR DESCRIPTION
**Pull request by ArtskydJ**
Fixes #230. Supersedes #231.

### CODE REVIEW

**Comment by puzrin** [comment]
Thanks! I plan to make release after #228 fixed or in a week.

**Comment by TehShrike** [comment]
Would you be willing to release this change as a patch version, and release #228 afterward as a feature/minor version?

**Comment by puzrin** [comment]
I'd prefer to increase minor version for this change too.

**Comment by TehShrike** [comment]
Fair enough.

**Comment by TehShrike** [comment]
Any chance this could make it to npm?

**Comment by puzrin** [comment]
That does not work well, because replace module with {} instead if ignoring. It became a problem, when you do really need to use esprima. Replaced your commit with https://github.com/nodeca/js-yaml/commit/6bdb5e79ecd532301a9c2b69c902f35ac72e5455

**Pull request merged**
